### ISSUE TITLE
Missing value lists for Inv/Fish/Herp

### ISSUE THREAD

**Issue by caalle** [DINA-Web/datasets#3]
Inv/Fish/Herp collection is missing:
- Type Status
- Life stage
- Sex

**Comment by caalle** [comment]
Is this something you could look at @jmenglund @lisasund ? Or who is the best person to provide the lists?

**Comment by caalle** [comment]
Any update on this?

**Comment by lisasund** [comment]
I just started to look at it today. Can provide some data tomorrow!

**Comment by caalle** [comment]
Can this be closed? @lisasund
